[project]
name = "comfydock"
version = "0.3.3"
description = "ComfyDock CLI"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.1.8",
    "comfydock-server>=0.3.2",
    "packaging>=24.2",
    "pydantic>=2.10.6",
    "python-dotenv>=1.0.1",
    "setuptools>=80.9.0",
]

[project.scripts]
comfydock = "comfydock.cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
