[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "python-data-augmenter"
version = "0.0.1"
description = "This library provides a set of tools for data augmentation, including text generation, data processing, and integration with multiple AI providers."
readme = "README.md"
authors = [{ name = "Marcos Cobo Carrillo", email = "mcobo@cic.es" }]
license-files = ["LICENSE.txt"]
dependencies = ["pandas", "numpy", "requests", "tqdm", "scikit-learn", "sentence-transformers", "rich", "pyyaml", "langchain-community", "langchain", "pymupdf", "openai"]
keywords = ["Augmentation", "GenAI", "Data", "Analytics", "ELFMo"]
urls = { "CIC" = "https://cic.es", "ELFMo" = "https://elfmo.eu", "Source" = "https://github.com/CIC-SL/python-data-augmenter", "Changelog" = "https://github.com/CIC-SL/python-data-augmenter/blob/main/CHANGELOG.md" }
classifiers = ["Programming Language :: Python :: 3", "License :: OSI Approved :: MIT License", "Intended Audience :: Developers"]
requires-python = ">=3.9"

[tool.setuptools]
packages = ["augmenter"]