[project]
name = "more-tk"
version = "0.1.2"
description = "A project made to replicate tkinter but with different commands."
authors = [
    {name = "Olivier Corbeil", email = "olicorb2000@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[tool.poetry]
packages = [{ include = "more_tk" }]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
