[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "midastrader"  
version = "1.0.29" 
description = "A robust backtesting and live trading engine designed for seamless strategy development and deployment. It supports user-defined strategies, multi-threaded execution, and integrations with brokers and data sources."  
readme = "README.md"  
keywords = ["algorithmic-trading","event-driven-backtest", "quantitative-finance", "finance", "markets"]  
license = { text = "Apache-2.0" }
authors = [
    { name = "Anthony Baxter", email = "anthonybaxter819@gmail.com" }
]
requires-python = ">=3.10"  
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent"
]
dependencies = [
    "aiohttp==3.9.5",
    "aiosignal==1.3.1",
    "appdirs==1.4.4",
    "arch==7.0.0",
    "async-timeout==4.0.3",
    "attrs==23.2.0",
    "backports.tarfile==1.2.0",
    "beautifulsoup4==4.12.3",
    "Brotli==1.1.0",
    "certifi==2024.7.4",
    "cffi==1.17.1",
    "chardet==5.2.0",
    "charset-normalizer==3.3.2",
    "contourpy==1.2.1",
    "cramjam==2.8.3",
    "cryptography==44.0.1",
    "cssselect2==0.7.0",
    "cycler==0.12.1",
    "databento==0.33.0",
    "databento-dbn==0.17.1",
    "docutils==0.21.2",
    "exchange_calendars==4.6",
    "fastparquet==2024.5.0",
    "fonttools==4.51.0",
    "frozendict==2.4.2",
    "frozenlist==1.4.1",
    "fsspec==2024.9.0",
    "html5lib==1.1",
    "ibapi==10.30.1",
    "idna==3.7",
    "importlib_metadata==8.6.1",
    "jaraco.classes==3.4.0",
    "jaraco.context==6.0.1",
    "jaraco.functools==4.1.0",
    "jeepney==0.8.0",
    "joblib==1.4.2",
    "keyring==25.6.0",
    "kiwisolver==1.4.5",
    "korean-lunar-calendar==0.3.1",
    "lxml==5.2.1",
    "markdown-it-py==3.0.0",
    "matplotlib==3.9.0",
    "mbinary==1.0.26",
    "mdurl==0.1.2",
    "midas_client==1.0.22",
    "more-itertools==10.5.0",
    "multidict==6.0.5",
    "multitasking==0.0.11",
    "nh3==0.2.20",
    "numpy==1.26.4",
    "packaging==24.1",
    "pandas==2.2.2",
    "pandas_market_calendars==4.4.2",
    "patsy==0.5.6",
    "peewee==3.17.3",
    "pillow==10.3.0",
    "pkginfo==1.12.0",
    "pyarrow==17.0.0",
    "pycparser==2.22",
    "pydyf==0.10.0",
    "Pygments==2.19.1",
    "pyluach==2.2.0",
    "pyparsing==3.1.2",
    "pyphen==0.15.0",
    "pyproject_hooks==1.2.0",
    "python-dateutil==2.9.0.post0",
    "python-decouple==3.8",
    "python-dotenv==1.0.1",
    "pytz==2024.1",
    "quant_analytics==1.0.7",
    "readme_renderer==44.0",
    "reportlab==4.2.0",
    "requests==2.32.3",
    "requests-toolbelt==1.0.0",
    "rfc3986==2.0.0",
    "rich==13.9.4",
    "scikit-learn==1.4.2",
    "scipy==1.13.0",
    "seaborn==0.13.2",
    "SecretStorage==3.3.3",
    "six==1.16.0",
    "soupsieve==2.5",
    "statsmodels==0.14.2",
    "threadpoolctl==3.5.0",
    "tinycss2==1.3.0",
    "toml==0.10.2",
    "toolz==1.0.0",
    "tzdata==2024.1",
    "urllib3==2.3.0",
    "weasyprint==62.1",
    "webencodings==0.5.1",
    "XlsxWriter==3.2.0",
    "yarl==1.9.4",
    "yfinance==0.2.38",
    "zipp==3.21.0",
    "zopfli==0.2.3",
    "zstandard==0.22.0"
]
