[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sc_utility"
version = "1.1.8"
description = "Shared utilities for logging and configuration management"
authors = [{ name = "Nick Elsey", email = "nick@spelloconsulting.com" }]
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.8"
dependencies = [
    "cerberus>=1.3.7",
    "openpyxl>=3.1.5",
    "pandas>=2.0.3",
    "pyyaml>=6.0.2",
    "requests>=2.32.3",
    "tzdata>=2025.2",
]

[project.urls]
Homepage = "https://github.com/NickElseySpelloC"
Repository = "https://github.com/NickElseySpelloC/sc_utility"

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]
