[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ro-lib"
version = "1.1.0"
description = "private roblox library"
requires-python = ">=3.7"
license = {text = "MIT"}
dependencies = [
    "aiohttp>=3.8.0"
]
authors = [
    {name = "Andrew Petty", email = "andrewtpetty03@gmail.com"}
]

[project.optional-dependencies]
test = [
    "pytest>=7.0.0",
    "pytest-asyncio>=0.20.0"
]

[tool.hatch.build.targets.wheel]
packages = ["ro_lib"]

[project.urls]
Homepage = "https://github.com/vangauthic/ro-lib/"