[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "validatrix"
version = "0.2.67"
description = "A Python library for using validatrix emulation hardware"
readme = "README.md"
requires-python = ">=3.6"
license = {text = "MIT"}
authors = [
    {name = "Prateek Pawar", email = "prateekspawar@gmail.com"},
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "python-can>=4.0.0",
    "cantools>=36.0.0",
    "adafruit-circuitpython-mcp4725>=1.4.6",
    "adafruit-blinka>=8.0.0",
    "pymodbus==3.1.3",
    "pyserial>=3.5",
    "asyncio>=3.4.3",
]

[project.urls]
Homepage = "https://github.com/prateekspawar/validatrix_python"
Repository = "https://github.com/prateekspawar/validatrix_python.git" 