[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
[project]
name = "mosaic-qt6"
version = "1.0.0"
authors = [
  { name="DCreator112", email="dylanlmclark@gmail.com" },
]
description = "Create Qt6 GUIs using HTML-like syntax!"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "BeautifulSoup4",
    'PySide6',
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://dcreator112.xyz/mosaic"