[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"


[project]
name = "fleascope-live-display"
version = "0.0.2"
authors = [
  { name="D. Freiermuth", email="author@example.com" },
]
description = "Oscilloscope frontend for FleaScope"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/daniel-freiermuth/fleascope-live"
Issues = "https://github.com/daniel-freiermuth/fleascope-live/issues"
