[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "sqlrender"
version = "1.0.2"
description = "Simple and fast sql templating engine inspired by the classical library MyBatis."
readme = "README.md"
license = { file = "LICENSE" }
authors = [
    { name = "Jiri Kacirek", email = "kacirek.j@gmail.com" }
]
requires-python = ">=3.6"
dependencies = [
    "bottle",
]

[project.urls]
Homepage = "https://github.com/kacirekj/sqlrender"
