[tool.poetry]
name = "pinhole-distance"
version = "0.1.1"
description = "A Python library for object distance calculations in images using pinhole projection."
authors = ["Michael Torres"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.7"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
