[tool.black]
line-length = 120

[project]
name = "pyrsistent_as_rpds_py"
version = "2.1.0"
description = "Adapter which implements a subset of rpds-py using pyrsistent. Mostly meant for PyPy."
readme = "README.md"
license = { text = "MIT" }
authors = [
    { name = "Eduard Christian Dumitrescu", email = "eduard.c.dumitrescu@gmail.com" },
]
maintainers = [
    { name = "Eduard Christian Dumitrescu", email = "eduard.c.dumitrescu@gmail.com" },
]
classifiers = [
    "Programming Language :: Python :: 3"
]
dependencies = []

[project.optional-dependencies]
pure       = ["pyrsistent"]
pyrsistent = ["pyrsistent"]
rpds-py = ["rpds-py"]

[project.urls]
Homepage = "https://github.com/e-c-d/pyrsistent-as-rpds-py/"

[project.scripts]
# your_executable_name = "rpds.cli:app"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.package-data]
"*" = ["*.*"]
