[build-system]
requires = ["setuptools>=61.0", "wheel", "build"]
build-backend = "setuptools.build_meta"

[project]
name = "spdx-license-matcher"
version = "1.0.8"
description = "Tool for matching and working with SPDX licenses"
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
authors = [{ name = "Sean Ross-Ross" }]
classifiers = ["Intended Audience :: Developers"]
dependencies = ["lxml~=5.4.0", "click~=8.2.1"]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "black>=23.0.0",
    "isort>=5.10.0",
    "mypy>=1.0.0",
    "ruff>=0.0.250",
]

[project.urls]
Source = "https://github.com/openteamsinc/spdx_matcher"

[tool.setuptools]
packages = ["spdx_license_matcher", "spdx_license_matcher.licenses"]
include-package-data = true

[tool.setuptools.package-data]
"spdx_license_matcher.licenses" = ["*.xml"]
"spdx_license_matcher" = ["py.typed"]

[tool.flake8]
max-line-length = 120

[tool.black]
line-length = 120

[project.scripts]
spdx-match = "spdx_license_matcher.main:cli"
