[tool.poetry]
name = "phenodig"
version = "0.3.5"
description = ""
authors = ["Gioele Lazzari"]
license = "GNU General Public License v3.0"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9"
pandas = ">=2.0.0"
openpyxl = ">=3.1.0"
scipy = ">=1.10.0"
biopython = ">=1.80"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
phenodig = "phenodig:main"
