[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["mosaic*"]

[project]
name = "mosaic-mmrag"
version = "0.2.0"
description = "Use late-interaction multi-modal models such as ColPali & ColQwen2 for retrieval, with Qdrant as a backend."
authors = [{ name = "Abdullah Meda", email = "abdullah.meda@gmail.com" }]
readme = "README.md"
requires-python = ">=3.9"
license = { file = "LICENSE" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]
dependencies = [
    "pdf2image",
    "qdrant-client>=1.13.3",
    "gotenberg-client>=0.10.0",
]

[project.optional-dependencies]
dev = ["pytest>=7.4.0", "ruff>=0.1.9"]
server = ["uvicorn", "fastapi"]
local = ["colpali_engine>=0.3.8"]
# gpu = ["flash-attn>=2.0.0"]

[project.urls]
"Homepage" = "https://github.com/abdullahmeda/mosaic"
"Bug Tracker" = "https://github.com/abdullahmeda/mosaic/issues"
