[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "file-captain"
dynamic = ["version"]
description = "Utility function to read and write files"
authors = [
    {name = "Philip Gautschi", email = "philips.python.projects@gmail.com"},
    {name = "Nicolas Brehm", email = "philips.python.projects+friends@gmail.com"},
]
maintainers = [
    {name = "Philip Gautschi", email = "philips.python.projects@gmail.com"},
]
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.11"
dependencies = [
    "tomli-w>=1.0.0",
    "pyyaml>=6.0",
]
keywords = ["file", "io", "json", "yaml", "toml", "pickle", "text", "utilities"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: System :: Filesystems",
    "Topic :: Utilities",
    "Typing :: Typed",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
    "isort",
    "black",
    "mypy",
    "types-PyYAML",
]

[project.urls]
"Homepage" = "https://github.com/philipgautschi/file-captain"
"Repository" = "https://github.com/philipgautschi/file-captain"
"Issues" = "https://github.com/philipgautschi/file-captain/issues"

[tool.hatch.version]
path = "src/file_captain/__init__.py"

[tool.hatch.build.targets.wheel]
packages = ["src/file_captain"]

[tool.hatch.build.targets.wheel.force-include]
"src/file_captain/py.typed" = "file_captain/py.typed"

[tool.hatch.build]
exclude = [
  ".git",
  ".github",
  ".gitignore",
  ".idea",
  ".vscode",
  "tests",
  "__pycache__",
  "*.pyc",
  "*.pyo",
  "*.pyd",
  ".pytest_cache",
  ".coverage",
  ".mypy_cache",
  "*.egg-info",
  "dist",
  "build",
  ".ruff_cache",
  ".cursorignore",
  ".cursorindexingignore",
  ".pypirc",
]

