[project]
name = "mbls"
version = "0.0.10"
description = "Model-Based Local Search algorithm designer built on Routix"
readme = "README.md"
authors = [
    { name = "JuneTech", email = "junetech0@gmail.com" }
]
license = "MIT"
requires-python = "==3.11.*"
dependencies = [
    "routix>=0.0.10",
]

[project.urls]
Repository = "https://github.com/junetech/mbls.git"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "ortools>=9.12.4544",
    "pytest>=8.3.5",
    "pyyaml>=6.0.2",
    "types-protobuf>=6.30.2.20250516",
    "types-pyyaml>=6.0.12.20250402",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
python_functions = "test_*"
