[project]
name = "typing_tool"
version = "0.1.8"
description = "python typing tool"
authors = [
    { name = "luxuncang", email = "luxuncang@qq.com" },
]
dependencies = [
    "pydantic>=2.7.0",
    "typing-inspect>=0.9.0",
    "typing-extensions>=4.11.0",
]
requires-python = ">=3.10"
readme = "README.md"
homepage = "https://github.com/lacia-hIE/typing_tool"

[project.license]
text = "MIT"

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"

[tool.pdm]
distribution = true

[tool.pdm.scripts]
test = "python -m pytest"

[tool.pdm.dev-dependencies]
dev = [
    "pytest>=8.3.2",
]
