[project]
name = "starch"
version = "0.0.0dev16"
description = "A configurable formatter for decorative comment generation."
readme = "README.md"
authors = [
    { name = "K. LeBryce", email = "k.lebryce@pm.me" }
]
requires-python = ">=3.10"
dependencies = [
    "click>=8.2.1",
    "platformdirs>=4.3.8",
]

[project.scripts]
starch = "starch:formatter.cli"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = []
optional = []
