[build-system]
requires = ["setuptools>=61.0", "wheel"] 
build-backend = "setuptools.build_meta"

[project]
name = "PSL_Tracer"
version = "0.1.8"
description = "Custom PSL Tracers for Grasshopper"
readme = "README.md"
license = { file = "LICENSE" }
authors = [
  { name = "Niclas Brandt", email = "niclasbrandt97@gmail.com" },
]
dependencies = [
  "requests>=2.0",          # example dependencies
  "numpy>=1.20"
]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]
requires-python = ">=3.7"

