[build-system]
requires = ["setuptools>=65.5.1", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sqlalchemy_tx_context"
version = "1.0.0"
description = "Context-local session manager for SQLAlchemy AsyncSession"
readme = { file = "README.md", content-type = "text/markdown" }
authors = [
    { name = "QuisEgoSum", email = "subbotin.evdokim@gmail.com" },
]
license = "MIT"
requires-python = ">=3.9"
keywords = ["sqlalchemy", "async", "contextvars", "transaction", "session"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent",
    "Development Status :: 5 - Production/Stable",
]
dependencies = [
    "SQLAlchemy>=2.0.0"
]

[project.optional-dependencies]
dev = [
    "pytest>=8.0,<9.0",
    "pytest-asyncio>=1.0.0",
    "tox>=4.26.0",
    "pytest-cov>=6.0,<7.0",
    "ruff>=0.11.2",
    "black>=25.1.0",
    "build>=1.2.2",
    "twine>=6.1.0",
    "asyncpg>=0.29.0",
    "aiosqlite>=0.21.0",
    "pyright>=1.1.402"
]

[project.urls]
"Homepage" = "https://github.com/QuisEgoSum/sqlalchemy-tx-context"
"Repository" = "https://github.com/QuisEgoSum/sqlalchemy-tx-context"
"Documentation" = "https://github.com/QuisEgoSum/sqlalchemy-tx-context#readme"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
exclude = ["tests*", "example*"]

[tool.ruff]
target-version = "py39"
line-length = 88
src = ["src", "tests", "example"]
exclude = ["dist", ".venv"]

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B", "C4", "SIM", "TID", "T20", "ARG", "COM812", "D204"]
ignore = ["B008", "SIM102", "UP006", "UP007", "E501"]

[tool.ruff.lint.isort]
combine-as-imports = true
force-single-line = false
lines-between-types = 1

[tool.black]
line-length = 88
target-version = ["py39"]
skip-string-normalization = true
