[project]
name = "pytilpack"
dynamic = ["version"]
description = "Python Utility Pack"
license = {text = "MIT"}
authors = [
    {name = "aki.", email = "mark@aur.ll.to"}
]
readme = "README.md"
requires-python = ">=3.12,<4.0"
classifiers = [
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3 :: Only",
]
dependencies = [
    "typing-extensions>=4.0",
]

[project.optional-dependencies]
all = [
    "azure-identity>=1.23.0",
    "beautifulsoup4>=4.12",
    "bleach>=6.2",
    "fastapi>=0.111",
    "flask-login>=0.6",
    "flask>=3.0",
    "html5lib",
    "httpx",
    "markdown>=3.6",
    "msal>=1.32.3",
    "openai>=1.25",
    "pillow",
    "pytest",
    "pytest-asyncio",
    "pyyaml>=6.0",
    "quart>=0.20.0",
    "sqlalchemy>=2.0",
    "tabulate[widechars]>=0.9",
    "tiktoken>=0.6",
    "tinycss2>=1.4",
    "tqdm>=4.0",
    "uvicorn>=0.34.3",
]
bleach = [
    "bleach>=6.2",
]
beautifulsoup4 = [
    "beautifulsoup4>=4.12",
]
fastapi = [
    "fastapi>=0.111",
    "html5lib",
    "httpx",
]
flask = [
    "flask>=3.0",
    "flask-login>=0.6",
    "html5lib",
    "pytest",
]
htmlrag = [
    "beautifulsoup4",
]
markdown = [
    "markdown>=3.6",
    "bleach",
    "tinycss2",
]
openai = [
    "openai>=1.25",
]
pytest = [
    "pytest",
    "pytest-asyncio",
]
pyyaml = [
    "pyyaml>=6.0",
]
sqlalchemy = [
    "sqlalchemy>=2.0",
    "tabulate[widechars]>=0.9",
]
tiktoken = [
    "tiktoken>=0.6",
    "openai",
    "httpx",
    "pillow",
]
tqdm = [
    "tqdm>=4.0",
]
quart = [
    "quart>=0.20.0",
    "quart-auth>=0.11.0",
    "html5lib",
    "pytest",
    "uvicorn>=0.34.3",
]
msal = [
    "azure-identity>=1.23.0",
    "msal>=1.32.3",
]

[dependency-groups]
dev = [
    "aiosqlite>=0.21.0",
    "litellm>=1.72.4",
    "pyfltr>=1.6.0",
    "pytest-asyncio>=0.21.0",
    "types-bleach>=6.2.0.20241123",
    "types-markdown>=3.7.0.20241204",
    "types-pyyaml>=6.0.12.20241230",
    "types-tabulate>=0.9.0.20241207",
]

[tool.uv]
default-groups = ["dev"]

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"

[tool.pyfltr]
pyupgrade-args = ["--py312-plus"]
pylint-args = ["--jobs=4"]

[tool.isort]
profile = "black"

[tool.black]
target-version = ['py312']
skip-magic-trailing-comma = true

[tool.flake8]
max-line-length = 128
extend-ignore = "E203,"

[tool.mypy]
allow_redefinition = true
check_untyped_defs = true
ignore_missing_imports = true
strict_optional = true
strict_equality = true
warn_no_return = true
warn_redundant_casts = true
warn_unused_configs = true
show_error_codes = true

[tool.pytest.ini_options]
addopts = "--showlocals -p no:cacheprovider --durations=5 -vv"
xfail_strict = true
log_level = "DEBUG"
asyncio_mode = "strict"
asyncio_default_fixture_loop_scope = "module"
