[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "python-viem"
version = "0.1.1"
description = "Python library for viem chain metadata, enabling compatibility with Javascript tooling."
readme = "README.md"
requires-python = ">=3.7, <4.0"
dependencies = [
    "requests>=2.31.0",
]

[project.license]
text = "MIT"

authors = [
    { name = "Brandyn Hamilton", email = "brandynham1120@gmail.com" }
]

dependencies = [
    "requests"
]

[tool.setuptools.packages.find]
include = ["python_viem", "python_viem.*"]

[tool.setuptools.package-data]
python_viem = ["viem-chains.json"]

[dependency-groups]
dev = [
    "build>=1.1.1",
    "twine>=4.0.2",
]

[tool.setuptools]
include-package-data = true

[project.optional-dependencies]
dev = [
    "build>=1.1.1",
    "twine>=4.0.2",
]
