[tool.poetry]
name = "bioplumber"
version = "1.3.3"
description = ""
authors = ["ParsaGhadermazi <54489047+ParsaGhadermazi@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.32.3"
rich = "^13.8.1"
ipywidgets = "^8.1.5"
textual = {version = "1.0.0", extras = ["syntax"]}
pandas = "^2.2.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
pipit = 'bioplumber.tui:main'
file-mgr = 'bioplumber.file_studio:main'