[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "ddnnife-cli"
version = "0.0.1"
authors = [
  { name="Tobias HeÃŸ", email="tobias.hess@variability.dev" },
]
description = "This package provides a CLI wrapper for the ddnnife Docker container."
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICENSE"]

[project.urls]
Homepage = "https://github.com/obddimal/ddnnife-cli"
Issues = "https://github.com/obddimal/ddnnife-cli/issues"