[project]
name = "yamlql"
version = "0.1.1"
description = "Query YAML files with SQL"
authors = [
    { name = "Sarav", email = "sarav@users.noreply.github.com" },
]
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "duckdb>=0.9.0",
    "pyyaml>=6.0",
    "typer>=0.9.0",
    "pandas>=2.0.0",
    "rich>=13.0.0",
    "python-dotenv>=1.1.0",
    "openai>=1.86.0",
    "google>=3.0.0",
    "google-generativeai>=0.8.5",
    "urllib3<2.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
]
nlp = [
    "python-dotenv>=1.0.0",
    "openai>=1.0.0",
    "google-generativeai>=0.5.0",
]

[project.scripts]
yamlql = "yamlql_library.cli:app"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["yamlql_library*"] 
